# Character Spark Tables Data
# This file contains all the spark table data separated from the code

SPARK_TABLES = {
    "evocative_adjectives": [
        "Brooding", "Flamboyant", "Calculating", "Restless", "Enigmatic", "Weathered", "Graceful", "Haunted",
        "Boisterous", "Methodical", "Impulsive", "Serene", "Fierce", "Melancholic", "Whimsical", "Stoic",
        "Ambitious", "Cautious", "Rebellious", "Wise", "Naive", "Cynical", "Optimistic", "Paranoid",
        "Charming", "Gruff", "Elegant", "Rustic", "Scholarly", "Primal", "Refined", "Wild",
        "Mysterious", "Transparent", "Complex", "Simple", "Dramatic", "Understated", "Bold", "Timid",
        "Ancient", "Youthful", "Experienced", "Fresh", "Battle-worn", "Untested", "Legendary", "Forgotten",
        "Noble", "Common", "Exotic", "Familiar", "Dangerous", "Harmless", "Intense", "Laid-back",
        "Passionate", "Detached", "Loyal", "Fickle", "Honest", "Deceptive", "Generous", "Selfish",
        "Patient", "Hasty", "Gentle", "Harsh", "Humble", "Proud", "Curious", "Indifferent",
        "Brave", "Cowardly", "Clever", "Foolish", "Lucky", "Cursed", "Blessed", "Doomed",
        "Radiant", "Shadow-touched", "Storm-blessed", "Earth-bound", "Fire-hearted", "Ice-cold", "Star-kissed", "Moon-touched",
        "Raven-haired", "Golden", "Silver-tongued", "Iron-willed", "Diamond-hard", "Silk-soft", "Thunder-voiced", "Whisper-quiet",
        "Sword-sworn", "Spell-touched", "God-marked", "Demon-scarred", "Angel-blessed", "Fey-touched", "Dragon-blooded", "Giant-born",
        "Tide-turned", "Wind-walked", "Stone-hearted", "Flame-kissed", "Frost-born", "Lightning-struck", "Earthquake-shaken", "Volcano-forged"
    ],
    
    "backgrounds_origins": [
        "Exiled Noble", "Guild Apprentice", "Bastard Heir", "Caravan Guard", "Street Orphan", "Temple Acolyte",
        "Merchant's Child", "Soldier's Offspring", "Tavern Keeper", "Blacksmith's Apprentice", "Scholar's Student", "Sailor's Mate",
        "Forest Hermit", "Mountain Dweller", "Desert Nomad", "Swamp Witch", "Cave Dweller", "Tower Scholar",
        "Royal Spy", "Rebel Fighter", "Cult Survivor", "Plague Doctor", "War Refugee", "Lost Explorer",
        "Circus Performer", "Gladiator Slave", "Pirate's Heir", "Smuggler's Child", "Thief Lord", "Assassin's Shadow",
        "Beast Tamer", "Dragon Rider", "Demon Hunter", "Ghost Whisperer", "Relic Seeker", "Tomb Robber",
        "Court Jester", "Royal Guard", "Diplomatic Envoy", "Foreign Ambassador", "Traveling Judge", "Bounty Hunter",
        "Plague Survivor", "Disaster Witness", "Miracle Child", "Prophesy Bearer", "Chosen One", "Marked Child",
        "Time Traveler", "Dimension Walker", "Plane Shifter", "Reality Bender", "Fate Weaver", "Destiny Changer",
        "Storm Caller", "Earth Shaker", "Fire Bringer", "Water Walker", "Wind Rider", "Shadow Dancer",
        "Light Bearer", "Dark Walker", "Void Toucher", "Star Reader", "Moon Singer", "Sun Worshipper",
        "Ancient Bloodline", "Lost Kingdom", "Hidden Village", "Secret Society", "Forgotten Order", "Banned Brotherhood",
        "Cursed Family", "Blessed Lineage", "Marked Clan", "Chosen House", "Sacred Tribe", "Damned Dynasty",
        "Foreign Land", "Distant Shore", "Unknown Realm", "Hidden Valley", "Lost City", "Forgotten Empire",
        "Sky Island", "Underground Kingdom", "Floating Castle", "Moving City", "Vanished Village", "Timeless Tower",
        "Dream Walker", "Nightmare Survivor", "Vision Seeker", "Oracle's Child", "Seer's Apprentice", "Prophet's Heir",
        "God's Champion", "Devil's Bargain", "Angel's Gift", "Demon's Mark", "Spirit's Chosen", "Ghost's Vengeance"
    ],
    
    "distinctive_traits": [
        "never removes their gloves", "speaks only in questions", "counts everything twice", "always knows true north",
        "can't cross running water without praying", "tastes food before anyone else eats", "sleeps with one eye open",
        "never sits with their back to a door", "always carries exactly seven coins", "speaks to animals like people",
        "draws maps of everywhere they go", "collects interesting stones", "knows a song for every occasion",
        "remembers every face they've ever seen", "can predict weather by joint pain", "never breaks a promise",
        "always tells the truth, even when it hurts", "laughs at their own jokes", "quotes dead philosophers",
        "carves their initials in new places", "always pays their debts immediately", "never gambles with money",
        "reads everything backwards first", "knocks three times before entering", "never eats meat on certain days",
        "whispers to their weapons", "names all their possessions", "keeps a detailed journal", "draws portraits of strangers",
        "never travels the same path twice", "always helps lost children", "feeds stray animals", "lights candles for the dead",
        "never lies to children", "always shares food with the hungry", "gives coins to beggars", "helps strangers in need",
        "remembers everyone's birthday", "knows the names of all the stars", "can find water in any desert",
        "always knows what time it is", "never gets lost in cities", "can sleep anywhere", "wakes at exactly dawn",
        "never forgets a kindness", "always repays cruelty", "keeps their word no matter the cost", "protects the innocent",
        "challenges bullies", "stands up for the weak", "never abandons a friend", "keeps others' secrets",
        "sees good in everyone", "trusts too easily", "forgives too quickly", "loves too deeply",
        "fears commitment", "avoids crowds", "distrusts authority", "questions everything", "believes in luck",
        "sees omens everywhere", "follows ancient customs", "respects old traditions", "honors the ancestors"
    ],
    
    "secret_motivations": [
        "seeks redemption for a terrible mistake", "hunts the one who killed their family", "protects a dangerous secret",
        "searches for their true parentage", "aims to restore their family's honor", "tries to break an ancient curse",
        "wants to prove their worth to a parent", "seeks to avenge a betrayed mentor", "hopes to find a lost love",
        "dreams of building a perfect kingdom", "plans to overthrow a tyrant king", "works to prevent a prophecy",
        "tries to save their homeland from disaster", "seeks immortality to protect others", "wants to become a god",
        "hopes to resurrect a dead friend", "tries to forget a traumatic past", "seeks to master forbidden knowledge",
        "wants to unite warring tribes", "hopes to find a legendary artifact", "tries to close a demon portal",
        "seeks to cure a magical disease", "wants to explore unknown lands", "hopes to make their mark on history",
        "tries to escape their dark destiny", "seeks to fulfill a sacred vow", "wants to earn a place in legend",
        "hopes to find meaning in existence", "tries to understand their strange dreams", "seeks to control their powers",
        "wants to protect future generations", "hopes to right an ancient wrong", "tries to heal the world's wounds",
        "seeks to bridge different worlds", "wants to transcend mortal limitations", "hopes to achieve perfect balance",
        "tries to preserve dying knowledge", "seeks to create something eternal", "wants to inspire others to greatness",
        "hopes to find their true calling", "tries to escape a binding oath", "seeks to free enslaved people",
        "wants to establish a new religion", "hopes to discover new magic", "tries to map the entire world",
        "seeks to commune with the gods", "wants to tame wild beasts", "hopes to sail uncharted seas",
        "tries to climb impossible peaks", "seeks to solve ancient mysteries", "wants to write the perfect song",
        "hopes to paint ultimate beauty", "tries to craft legendary weapons", "seeks to brew perfect potions",
        "wants to grow magical gardens", "hopes to train perfect warriors", "tries to teach wisdom to fools"
    ],
    
    "notable_possessions": [
        "a locket that won't open", "a sword with a chipped blade", "a map to nowhere", "a key without a lock",
        "a book written in unknown language", "a compass that points to lost things", "a mirror that shows truth",
        "a coin that always lands heads", "a feather that never falls", "a stone that feels warm",
        "a ring that changes color with mood", "a pendant that glows at midnight", "a bracelet of silver bells",
        "a hat that's seen better days", "a cloak that never gets wet", "boots that never wear out",
        "gloves that never come off", "a mask with no eye holes", "a blindfold that helps you see",
        "spectacles that reveal magic", "a monocle that magnifies truth", "a pipe that never needs tobacco",
        "a flask that refills itself", "a purse that's always nearly empty", "a bag that holds impossible things",
        "a rope that never tangles", "a hammer that sings when it strikes", "a chisel that carves memories",
        "a paintbrush that paints the future", "a quill that writes by itself", "ink that changes color daily",
        "a candle that never burns out", "a lantern that shows hidden paths", "a torch that burns cold",
        "a blanket that brings good dreams", "a pillow that prevents nightmares", "a teddy bear with button eyes",
        "a wooden horse on wheels", "a set of dice that feel lucky", "a deck of cards missing the ace",
        "a chess set with living pieces", "a music box that plays lullabies", "a snow globe with moving figures",
        "a telescope that sees yesterday", "a sundial that works at night", "an hourglass that runs backwards",
        "a weather vane that predicts hearts", "a door knocker that answers back", "a bell that rings for danger",
        "a horn that calls the wind", "a drum that thunders like storms", "a flute that charms wild beasts"
    ],
    
    "fears_weaknesses": [
        "terrified of deep water", "cannot stand the sight of blood", "freezes when confronted with spiders",
        "loses speech when nervous", "becomes violently ill on boats", "faints at the sight of needles",
        "cannot sleep in complete darkness", "panics in enclosed spaces", "trembles at loud noises",
        "cannot lie convincingly", "trusts everyone immediately", "falls in love too easily",
        "always sees the best in people", "cannot say no to requests", "gives away money freely",
        "believes every sob story", "thinks everyone deserves redemption", "refuses to harm children",
        "won't fight on holy ground", "cannot break their word", "must help anyone in need",
        "compulsively tells the truth", "cannot ignore injustice", "always pays their debts",
        "haunted by recurring nightmares", "hears voices from the past", "sees ghosts of the dead",
        "cursed with prophetic dreams", "remembers other people's memories", "feels others' emotions",
        "cannot touch iron with bare skin", "weakened by running water", "burned by holy symbols",
        "loses power during eclipses", "strength fades in sunlight", "magic fails near churches",
        "allergic to silver", "poisoned by certain foods", "sickened by beautiful music",
        "ages rapidly when angry", "shrinks when afraid", "becomes invisible when embarrassed",
        "speaks only truth when drunk", "compelled to rhyme when excited", "cannot stop dancing to music",
        "must count everything they see", "organizes everything by color", "straightens crooked pictures",
        "washes hands obsessively", "checks locks multiple times", "counts steps while walking"
    ],
    
    "distinctive_mannerisms": [
        "drums fingers when thinking", "chews on their hair when nervous", "always sits facing the door",
        "taps their foot to unheard music", "speaks with their hands constantly", "never makes eye contact",
        "stares intensely when listening", "nods at everything said", "repeats the last word of sentences",
        "starts every sentence with 'Well...'", "ends questions with 'yes?'", "whispers when excited",
        "shouts when whispering would do", "laughs at inappropriate times", "cries during happy moments",
        "hums while working", "sings under their breath", "whistles complex melodies",
        "clicks their tongue when annoyed", "snorts when amused", "giggles nervously",
        "clears throat before speaking", "coughs to get attention", "sneezes when lying",
        "blushes when complimented", "turns pale when angry", "sweats when nervous",
        "twirls their hair around fingers", "braids and unbraids constantly", "adjusts their clothing obsessively",
        "polishes their weapons daily", "sharpens things when bored", "carves wood while talking",
        "draws in the dirt with sticks", "makes shadow puppets", "juggles random objects",
        "balances on narrow ledges", "climbs things unnecessarily", "always takes the high ground",
        "walks in perfect straight lines", "never steps on cracks", "avoids walking under things",
        "opens every door they pass", "looks behind every curtain", "investigates every noise",
        "tastes everything before eating", "smells books before reading", "touches textures compulsively",
        "collects shiny objects", "hoards useful items", "never throws anything away"
    ],
    
    "relationships_connections": [
        "owes a life debt to a stranger", "promised their dying mother something impossible", "sworn enemy of a childhood friend",
        "secretly related to a famous villain", "was engaged to someone they've never met", "has a twin they've never known",
        "trained by a legendary master", "betrayed their best friend for gold", "saved a prince in disguise",
        "shared a cell with a notorious criminal", "learned magic from a dying wizard", "inherited a cursed bloodline",
        "bound by oath to a mysterious order", "seeking revenge for a murdered sibling", "protecting the identity of a hero",
        "carrying a message for a dead man", "searching for their lost mentor", "fleeing from their own wedding",
        "hunting the beast that killed their village", "following clues left by their father", "guided by their grandmother's ghost",
        "competing with their perfect sibling", "trying to impress their disappointed parent", "living up to their ancestor's legend",
        "making amends to their former victim", "repaying kindness shown by a beggar", "fulfilling a promise to a dying enemy",
        "secretly funding an orphanage", "anonymously helping their hometown", "protecting their younger cousin",
        "corresponding with a foreign spy", "allied with an unlikely companion", "indebted to a crime lord",
        "blackmailed by someone from their past", "knows a terrible secret about a leader", "witnessed something they shouldn't have",
        "carrying letters for forbidden lovers", "smuggling refugees to safety", "hiding a political fugitive",
        "harboring a magical creature", "protecting an ancient artifact", "guarding a dangerous secret",
        "member of a secret society", "initiate of a mystery cult", "student of forbidden arts",
        "chosen champion of a minor god", "cursed by a spurned lover", "blessed by a grateful parent"
    ]
}